import './js/hero-filter.js';
import './js/hero-search.js';
import './js/events.js';
import './js/main.js';
import './js/pagination.js';
import './js/buy-tickets.js';
import './js/modal.js';
import './js/modal-team.js';
import './js/loading.js';
